name: CI

on: [push]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        spark-version: ['2.4.6', '3.0.0']
        scala-version: ['2.11.12', '2.12.10']
        python-version: ['3.6']
        exclude:
          - spark-version: '3.0.0'
            scala-version: '2.11.12'
        include:
          - spark-version: '2.4.6'
            spark-compat-version: '2.4'
          - spark-version: '3.0.0'
            spark-compat-version: '3.0'

          - scala-version: '2.11.12'
            scala-compat-version: '2.11'
          - scala-version: '2.12.10'
            scala-compat-version: '2.12'

    name: Build and Test (Spark ${{ matrix.spark-version }} Scala ${{ matrix.scala-version }} Python  ${{ matrix.python-version }})
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set versions in pom.xml
      run: |
        ./set-version.sh ${{ matrix.spark-version }} ${{ matrix.scala-version }}
        git diff

    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python/requirements-${{ matrix.spark-compat-version }}_${{ matrix.scala-compat-version }}.txt
        pip install pytest

    - name: Scala Tests
      run: mvn --batch-mode test

    - name: Python Tests
      env:
        PYTHONPATH: python:python/test
      run: |
        mkdir -p target/surefire-reports
        python -m pytest python/test --junit-xml target/surefire-reports/pytest.xml

    - name: Publish Unit Test Results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@master
      with:
        check_name: Unit Test Results (Spark ${{ matrix.spark-version }} Scala ${{ matrix.scala-version }} Python  ${{ matrix.python-version }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: "target/surefire-reports/*.xml"

    - name: Generate Unit Test Report
      if: failure()
      run: mvn --batch-mode surefire-report:report-only

    - name: Upload Unit Test Results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results (Spark ${{ matrix.spark-version }} Scala ${{ matrix.scala-version }} Python  ${{ matrix.python-version }})
        path: |
          target/surefire-reports/*.xml
          !target/surefire-reports/TEST-org.scalatest*.xml
          target/site/surefire-report.html
