name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python/requirements.txt
        pip install pytest

    - name: Build and Test
      run: mvn --batch-mode test

    - name: PyTest
      env:
        PYTHONPATH: python:python/test
      run: |
        mkdir -p target/surefire-reports
        python -m pytest python/test --junit-xml target/surefire-reports/pytest.xml

    - name: Upload Test Results
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results
        path: |
          target/surefire-reports/*.xml
          !target/surefire-reports/TEST-org.scalatest*.xml

    - name: Test Report
      if: ${{ failure() }}
      run: mvn --batch-mode surefire-report:report-only

    - name: Upload Report
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results
        path: target/site/surefire-report.html

    - name: Unit Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1.0.3
      with:
        check_name: Unit Test Report
        github_token: ${{ secrets.GITHUB_TOKEN }}
        report_paths: "**/surefire-reports/*.xml"
